apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apic-pipeline-git
  namespace: ci
spec:
  encryptedData:
    GIT_PRIV_TOKEN: AgCRLdA14DgbPX4rvzGWGU3NZYesSHbyeLEHsNgsRxKBpCIOTlaisoPg0gR06XfGgHAyTysUyeMARMBzxuoeU5KeDptMFsPW7ZQwg7OPYGs4zxlMcnEvUla0uvsFgwHb1IQHnMEwgz8CduQJpAachLDmN/UtLds2IR7oWgXt5OnhV+FrVZTsAmu7cF1p/TO8FwW92NKH/AiKbITgIIerVsar4u2Zv10wqDnA+AHdruU2UgWbvkWWBC9xrhITgJ/hIp4bjkOBJ8UTkOd/V6IYX63H+9GDX8cBAqtZu3oO4DTeLmDSNw7Thqko+ajcQmmlzcE87YGP4xsX4B2rNewrIyFHZFLON1PrbRPARm9bW3zvdbFbPOFT3ALw6mQcIkQNbKoMJZ+sPUZ0Lxs3X1K9O/VBzQEPs54J9Nbz1n+n+rIXHp8yMJjJib558IPhwdGQtCf7ruQcTdadPfq7AUFOKuVUXz3xmh+k8rMvZ4wIK2azygV1mLKoh9tJeOlBQfOVV+o6VD25DS50czqAynC5XgbIKdGnTPBxoOcnpj/vZR4c+0OQQWWLqVnKgnA+kmtdlimMpAd9Egk6nB6fYtrRNUuWXBPYJBrW7jIpG+43JXB2IgFSWHoVv/96oDOwEr/UisQngykrD8v3IzCGmu0YF6v542x0fI9D2fIAtShBV3G3V2Ax6jqSaSY8fRfn4ZO7LN0z0VtK7NK1+wo7SazFBTkRWIu0tPpkPe4IiTDiXSoPAo1O0jwDr94b
    GIT_USERNAME: AgCOq48alBvubfWP33bFyx2FcTm73J4XpOI48MdgS1Ke2nKOLnrcTsuyHuJPTzv4spJZFEDLwsTA3UY7zJrxn01HY+QdfEXShFVfbUrzV8bM11w8JQqKD+V5i1tHUUgpwrbHYrRUI2A1srv5BftpB+i6UWTgE/8MZsOt1NevVRDEoto4n+zZg4aVrnGT3mMdkqbsjNwxrIJwZUT3Dk8q44JA1ACn3rD7i48tIZSb6tMUHUYrMPM8BWD7toKtBSZYfFZNQ8e3rucG8aQ5lFgWKZubCF7ADuk3EzVXW+fgTdle33uhcl9cIFnPrk0KEKAapvThcm/e2WHSXHBJO4PUU1OGYq7qyCeMC9DBXNqN+a+Lbdu5Ob17qouAmsrWmt2m8ctkdFcgoG/ldF9imI0aSr6+2/F5mdble63HOYVvHWmZYFW1nPAvkuv9idwLinzwk5xjjc6bZtAKmUhQfDopCiCj1o8kHMW6yqDUgwg9JOiQ/cbG9jMVD9FhvSZ+dWF8dJd+7n8aYyz6MRCyvC6frBk7dO+ynY0Gu5yZFPoql47DHSo8pXH7VaiEdVPg1K0rzbm9v6jtfmeTaYDcf9Cr7fvnanKmm+4K/hMNEUGcQZJxZqGsfhcRbPD9pRXjvGmmss/po1rdpvRgrrwLkv6nhkPOvs7gxKZ3P3qOJr02FePpnmBEGmBJCGIozURHwkDnUYIHlTt9d/qEwPAbenIg
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: apic-pipeline-git
      namespace: ci

